controllers:
  - name: 'FormationPathController'
    type: 'local_planner/FormationPathController'

# Default tolerance values that are used for the controller by MoveBaseFlex
dist_tolerance: 0.02 # Tolerance in [m]
angle_tolerance: 0.05 # Tolerance in [rad]

FormationPathController:
  max_vel_x:  0.8

  # This parameter is only necessary if move-base pkg is used, for move-base-flex please use dist_tolerance
  # Parameter is defining the tolerance when arriving at the goal in the x and y direction.
  # Parameter is defined in meters
  xy_default_tolerance: 0.03 
  # This parameter is only necessary if move-base pkg is used, for move-base-flex please use angle_tolerance
  # Parameter is defining the tolerance when arriving at the goal for the orientation.
  # Parameter is defined in radian
  yaw_default_tolerance: 0.05 # ~3°

  formation_config:
    robot0:
      namespace: /robot0_ns
      master: true
      robot_pose_topic: amcl_pose
      robot_odom_topic: mobile_base_controller/odom
    robot1:
      namespace: /robot1_ns
      robot_pose_topic: amcl_pose
      robot_odom_topic: mobile_base_controller/odom
    robot2:
      namespace: /robot2_ns
      robot_pose_topic: amcl_pose
      robot_odom_topic: mobile_base_controller/odom