controllers:
  - name: 'FormationPathController'
    type: 'local_planner/FormationPathController'

# Default tolerance values that are used for the controller by MoveBaseFlex
dist_tolerance: 0.02 # Tolerance in [m]
angle_tolerance: 1.0 # Tolerance in [°]

FormationPathController:
  formation_config:
    robot0:
      namespace: /robot0_ns
      master: true
      robot_pose_topic: amcl_pose
    robot1:
      namespace: /robot1_ns
      robot_pose_topic: amcl_pose
    robot2:
      namespace: /robot2_ns
      robot_pose_topic: amcl_pose